version: "3.0"

services:
  api:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_PORT: 27017
      DB_HOSTNAME: db
      DB_NAME: votos
      JWT_SECRET: secreto123
    links:
      - db
    depends_on:
      - db
  db:
    image: mvertes/alpine-mongo
    volumes:
    - /tmp/mongodb:/data
    ports:
      - "27017:27017"

